version: '3.8'

services:
  aql_mailer:
    image: aql-mailer:latest
    container_name: cohort_data_mailer
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /opt/cohort_emailer/config/.env   # External .env path
    volumes:
      - /opt/cohort_emailer/data:/app/data                 # External DB folder
      - /opt/cohort_emailer/config/settings.yml:/app/config/settings.yml  # External settings
      - /opt/cohort_emailer/config/.env:/app/config/.env                   # Bind .env for internal access
      # - /opt/cohort_emailer/logs:/app/logs             # optional logs
    labels:
      maintainer: "Michael Anywar <michael.anywar@alpamax.eu>"
      project: "AQL Email Dispatcher"
    restart: unless-stopped
