aql:
  base_query: |
    SELECT e/ehr_status/subject/external_ref/id/value AS subjectID,
        c/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.case_identification.v0]/items[at0001]/value/value AS  encounter_id,
        c/content[openEHR-EHR-EVALUATION.problem_diagnosis.v1]/data[at0001]/items[at0002]/value/defining_code/code_string AS Condition_code,
        c/content[openEHR-EHR-EVALUATION.problem_diagnosis.v1]/data[at0001]/items[at0002]/value/value AS Condition_Display,
        c/content[openEHR-EHR-EVALUATION.problem_diagnosis.v1]/data[at0001]/items[at0002]/value/defining_code/terminology_id/value AS Condition_code_system, 
        c/content[openEHR-EHR-EVALUATION.problem_diagnosis.v1]/data[at0001]/items[at0003]/value/value AS Condition_recordedDate
    FROM EHR e
    CONTAINS VERSION v
    CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.report.v1] 
    WHERE c/name/value='Diagnose'
    AND c/content[openEHR-EHR-EVALUATION.problem_diagnosis.v1]/data[at0001]/items[openEHR-EHR-CLUSTER.problem_qualifier.v2]/items[at0063]/value/defining_code/code_stringe LIKE 'Z51.6'
    OR c/content[openEHR-EHR-EVALUATION.problem_diagnosis.v1]/data[at0001]/items[openEHR-EHR-CLUSTER.problem_qualifier.v2]/items[at0063]/value/defining_code/code_stringe LIKE 'E78.4'
    AND v/commit_audit/time_committed/value <='{start_time}'
    AND v/commit_audit/time_committed/value < '{end_time}'
    OFFSET 0 LIMIT 9000

openehr:
  url: ${OPENEHR_URL}
  username: ${OPENEHR_USERNAME}
  password: ${OPENEHR_PASSWORD}

email:
  exchange:
    server: ${EXCHANGE_SERVER}
    username: ${EXCHANGE_USERNAME}
    password: ${EXCHANGE_PASSWORD}
    sender: ${EXCHANGE_SENDER}

  subject: 'Project Data Export - {default_start}'
  body: |
    Hello,
    This is an automated email from the DataBank.
    Find attached the data export for your project for the period:
    From: {default_start}  To:   {now}

    Regards,
    System
  routing:
    - field: "Condition_code"
      values: ["E*", "Z*"]
      recipient: "reciepient1@mail.com"
  
    - field: "consent_type"
      values: ["E*", "Z*"]
      recipient: "mch@mail.eu"

job:
  db_path: "data/results.db"
  default_start: "2019-01-01T00:00:00Z"
  default_end: "2025-05-01T00:00:00Z"
  use_end_time: true
  interval_hours: 3   
  polling: false
  polling_hours: 23          # Defines time window from start_time

